# .rubocop.yml
# Подключите rubocop-rails, только если гем есть в Gemfile:
#   group :development do
#     gem "rubocop",       require: false
#     gem "rubocop-rails", require: false   # <= опционально
#   end

require:
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: <%= RUBY_VERSION.to_f %>
  SuggestExtensions: false

  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'public/**/*'

# -------- Автофиксируемые «безопасные» стили --------
Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
# -------- Частые отключения/настройки --------
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'test/**/*'

Metrics/MethodLength:
  Max: 20

# -------- Rails (работает только если есть rubocop-rails) --------
Rails:
  Enabled: true

Rails/SaveBang:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true
