version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUBY_VERSION: ${RUBY_VERSION:-3.3.9}
    env_file:
      - .env.prod
    environment:
      - PORT=3000
    depends_on:
      - db
    expose:
      - "3000"

  nginx:
    build:
      context: ./nginx
      #   dockerfile: Dockerfile.nginx  # default name; keep for clarity if renamed
      dockerfile: Dockerfile.nginx
    ports:
      - "${HTTP_PORT:-80}:80"
    environment:
      - UPSTREAM_HOST=${UPSTREAM_HOST:-web}
      - UPSTREAM_PORT=${UPSTREAM_PORT:-3000}
      - REAL_IP_FROM=${REAL_IP_FROM:-}
    depends_on:
      - web

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-app_production}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-app_production}" ]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
